# Setup
title:                  GW2Guias
description:            'Guias para Guild Wars 2'
author:
  name:                 'Angel Castillo'
  url:                  https://steamcommunity.com/id/ACast59/
  introduction:         'Just a newbie web dev / long time gamer.'  
paginate:               3
paginate_path:          '/pagina:num'
permalink:              /:categories/:title/
baseurl:                "/"
url:                    https://acast59.github.io/GW2Guias
paginate: 3
paginate_path: "/pagina:num/"
tag_page: '/etiquetas/'
category_page: '/categorias/'
